"""
Export all Supabase data for backup/handover purposes.

Usage:
    python -m scripts.export_data
    python -m scripts.export_data --output-dir /path/to/backup
    python -m scripts.export_data --include-vectors

Exports all application tables to JSON files inside a timestamped directory.
Use --include-vectors to also export vector embeddings (can be large).
Requires SUPABASE_URL and SUPABASE_SERVICE_KEY in the .env file.
"""

import argparse
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path

# Allow running from backend/ directory
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from supabase import create_client

from app.config import settings

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

TABLES = [
    "chat_sessions",
    "chat_messages",
    "documents_metadata",
    "glossary",
    "global_corrections",
    "message_feedback",
]


def validate_tables(client, tables: list[str]) -> list[str]:
    """Check which tables exist and are accessible. Returns list of valid tables."""
    valid = []
    for table in tables:
        try:
            client.table(table).select("id").limit(1).execute()
            valid.append(table)
        except Exception as e:
            logger.warning(f"  Table '{table}' skipped — {e}")
    return valid


def export_table(client, table_name: str) -> list[dict]:
    """Fetch all rows from a Supabase table. Returns empty list on failure."""
    try:
        response = client.table(table_name).select("*").execute()
        data = response.data
        logger.info(f"  {table_name}: {len(data)} rows")
        return data
    except Exception as e:
        logger.error(f"  {table_name}: failed to export — {e}")
        return []


def export_vectors(client, export_dir: Path) -> tuple[int, int]:
    """Export vector embeddings from wind_turbine_docs. Returns (row_count, file_size)."""
    try:
        logger.info("  Exporting vector embeddings (this may take a while)...")
        # Query the vecs schema directly via Supabase RPC or raw query
        # wind_turbine_docs stores: id, vec, metadata
        response = client.schema("vecs").from_("wind_turbine_docs").select("id,metadata").execute()
        data = response.data
        logger.info(f"  wind_turbine_docs: {len(data)} vectors (metadata only, vectors excluded for size)")

        output_file = export_dir / "wind_turbine_docs_metadata.json"
        content = json.dumps(data, indent=2, ensure_ascii=False, default=str)
        output_file.write_text(content, encoding="utf-8")

        return len(data), output_file.stat().st_size
    except Exception as e:
        logger.error(f"  Vector export failed: {e}")
        logger.info("  Tip: Vector embeddings can be regenerated by re-ingesting documents.")
        return 0, 0


def main():
    parser = argparse.ArgumentParser(description="Export Supabase data for backup")
    parser.add_argument(
        "--output-dir",
        default="./export",
        help="Base output directory (default: ./export)",
    )
    parser.add_argument(
        "--include-vectors",
        action="store_true",
        help="Also export vector metadata from wind_turbine_docs (can be large)",
    )
    args = parser.parse_args()

    # Validate config
    if not settings.supabase_url or not settings.supabase_service_key:
        logger.error("SUPABASE_URL and SUPABASE_SERVICE_KEY must be set in .env")
        sys.exit(1)

    start_time = time.time()

    # Create timestamped export directory
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    export_dir = Path(args.output_dir) / f"export_{timestamp}"
    export_dir.mkdir(parents=True, exist_ok=True)
    logger.info(f"Exporting to {export_dir}")

    # Connect to Supabase
    client = create_client(settings.supabase_url, settings.supabase_service_key)

    # Validate tables exist
    logger.info("Validating tables...")
    valid_tables = validate_tables(client, TABLES)
    logger.info(f"Found {len(valid_tables)}/{len(TABLES)} tables")

    # Export each table
    summary_lines = []
    total_size = 0

    for table_name in valid_tables:
        data = export_table(client, table_name)

        output_file = export_dir / f"{table_name}.json"
        content = json.dumps(data, indent=2, ensure_ascii=False, default=str)
        output_file.write_text(content, encoding="utf-8")

        file_size = output_file.stat().st_size
        total_size += file_size
        summary_lines.append(f"  {table_name}: {len(data)} rows ({file_size:,} bytes)")

    # Export vectors if requested
    if args.include_vectors:
        vec_count, vec_size = export_vectors(client, export_dir)
        total_size += vec_size
        summary_lines.append(f"  wind_turbine_docs: {vec_count} vectors ({vec_size:,} bytes)")

    elapsed = time.time() - start_time

    # Write summary report
    summary_path = export_dir / "export_summary.txt"
    summary = (
        f"Supabase Data Export Summary\n"
        f"{'=' * 40}\n"
        f"Export date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"Output dir:  {export_dir.resolve()}\n"
        f"Include vectors: {'Yes' if args.include_vectors else 'No'}\n\n"
        f"Tables:\n"
        + "\n".join(summary_lines)
        + f"\n\nTotal data size: {total_size:,} bytes\n"
        + f"Export time: {elapsed:.1f} seconds\n"
    )
    summary_path.write_text(summary, encoding="utf-8")

    logger.info(f"Export complete in {elapsed:.1f}s. Summary written to {summary_path}")
    print(f"\n{summary}")


if __name__ == "__main__":
    main()
