"""Standalone test harness for `is_qa_chunk` detection logic.

Pins the QA-corpus detection rule that lives at
    backend/app/services/qa_chunk.py:is_qa_chunk

This rule is the single decision point for "should this chunk be filtered
out before reranking?" — used by both AdvancedRetriever (services/
advanced_retriever.py) and QACorpusFilterPostprocessor (services/rag.py).
A silent change here would let AI-generated Q&A pairs leak into final
answers, displacing higher-quality handbook passages.

Usage
-----
    cd backend
    python scripts/test_qa_chunk.py
    python scripts/test_qa_chunk.py -v   # show passing test details

Exit codes
----------
    0  all assertions hold
    1  one or more assertions failed
    2  unable to import target module (env / dependency problem)

No network, no OpenAI key, no Supabase needed.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    from app.services.qa_chunk import is_qa_chunk  # noqa: E402
except Exception as exc:  # pragma: no cover - environment problem
    print(f"FAIL: could not import is_qa_chunk: {exc}")
    sys.exit(2)


# ── Stubs (mirrors test_citations.py for consistency) ─────────────────


class _StubNode:
    def __init__(self, filename: str | None, content: str) -> None:
        self.metadata: dict = {} if filename is None else {"filename": filename}
        self._content = content

    def get_content(self) -> str:
        return self._content


class _StubNodeWithScore:
    def __init__(self, filename: str | None, content: str, score: float = 0.5) -> None:
        self.node = _StubNode(filename, content)
        self.score = score


def make_node(filename: str | None, content: str) -> _StubNodeWithScore:
    return _StubNodeWithScore(filename, content)


# ── Test runner ────────────────────────────────────────────────────────


class Results:
    def __init__(self, verbose: bool) -> None:
        self.passed: list[str] = []
        self.failed: list[tuple[str, str]] = []
        self.verbose = verbose

    def check(self, name: str, condition: bool, detail: str = "") -> None:
        if condition:
            self.passed.append(name)
            if self.verbose:
                print(f"  PASS  {name}" + (f" — {detail}" if detail else ""))
        else:
            self.failed.append((name, detail))
            print(f"  FAIL  {name}" + (f" — {detail}" if detail else ""))

    def summary(self) -> int:
        total = len(self.passed) + len(self.failed)
        print()
        print(f"Summary: {len(self.passed)}/{total} passed")
        if self.failed:
            print("Failures:")
            for name, detail in self.failed:
                print(f"  - {name}: {detail}")
            return 1
        return 0


# ── Tests ──────────────────────────────────────────────────────────────


def test_is_qa_chunk(r: Results) -> None:
    print("\n[is_qa_chunk]")

    # 1. Filename starts with "qa" (the canonical case from ingest_qa.py)
    r.check(
        "filename 'qa_corpus/structure.md' detected",
        is_qa_chunk(make_node("qa_corpus/structure.md", "anything")),
    )

    # 2. Case-insensitive (rule lowercases filename before checking)
    r.check(
        "filename 'QA_corpus/x.md' detected (case-insensitive)",
        is_qa_chunk(make_node("QA_corpus/x.md", "anything")),
    )

    # 3. Non-QA filename ignored
    r.check(
        "filename 'handbook.pdf' not detected",
        not is_qa_chunk(make_node("handbook.pdf", "Some technical content.")),
    )

    # 4. Content prefix "Q:" detected even with no filename hint
    r.check(
        "content 'Q: ...' detected",
        is_qa_chunk(make_node("", "Q: What is yaw control?\nA: It aligns the rotor.")),
    )

    # 5. Content prefix "Q :" (with space) also detected
    r.check(
        "content 'Q : ...' detected (space variant)",
        is_qa_chunk(make_node("", "Q : What is pitch?\nA: Blade angle.")),
    )

    # 6. Leading whitespace stripped before prefix check
    r.check(
        "content '  Q: ...' detected (leading whitespace)",
        is_qa_chunk(make_node("", "  Q: leading whitespace test")),
    )

    # 7. Plain "A:" prefix is NOT a QA chunk (not generated by ingest_qa.py)
    r.check(
        "content 'A: ...' alone not detected",
        not is_qa_chunk(make_node("", "A: just an answer with no question prefix")),
    )

    # 8. Empty content + no filename → not a QA chunk
    r.check(
        "empty node not detected",
        not is_qa_chunk(make_node(None, "")),
    )

    # 9. Filename-first short-circuit: if filename matches, content is ignored
    r.check(
        "filename 'qa.md' wins over unrelated content",
        is_qa_chunk(make_node("qa.md", "totally unrelated handbook prose")),
    )


# ── Entry point ────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(description="QA detection test harness")
    parser.add_argument("-v", "--verbose", action="store_true", help="show passing tests")
    args = parser.parse_args()

    print("WINDBOT QA detection — pinning current behavior")
    print("=" * 60)

    r = Results(verbose=args.verbose)
    test_is_qa_chunk(r)
    return r.summary()


if __name__ == "__main__":
    sys.exit(main())
