"""Advanced Retriever: orchestrates the full retrieval pipeline.

Implements LlamaIndex's BaseRetriever interface so it plugs directly
into CondensePlusContextChatEngine. The pipeline uses speculative
execution to overlap multi-query generation with initial searches:

Phase A (parallel):
  - Dense + BM25 for original + expanded queries
  - Multi-Query LLM generation
Phase B (after multi-query returns):
  - Dense + BM25 for generated variant queries
Phase C:
  - RRF Fusion → QA Filter → VI Boost → Reranking
"""

import asyncio
import concurrent.futures
import logging
import time
from typing import Optional

from llama_index.core import VectorStoreIndex
from llama_index.core.retrievers import BaseRetriever
from llama_index.core.schema import NodeWithScore, QueryBundle
from openai import OpenAI
from supabase import Client as SupabaseClient

from app.services.bm25_search import BM25Searcher
from app.services.hybrid_search import merge_multi_query_results, reciprocal_rank_fusion
from app.services.qa_chunk import is_qa_chunk
from app.services.query_expansion import GlossaryExpander
from app.services.query_generation import generate_query_variants
from app.services.reranker import FlashReranker, OnnxReranker

logger = logging.getLogger(__name__)


class AdvancedRetriever(BaseRetriever):
    """Full pipeline retriever with hybrid search, reranking, and query expansion.

    Uses speculative execution: searches for the original query start
    immediately while multi-query variants are being generated by the LLM.
    """

    def __init__(
        self,
        index: VectorStoreIndex,
        supabase_client: SupabaseClient,
        glossary_expander: Optional[GlossaryExpander] = None,
        reranker: Optional[FlashReranker | OnnxReranker] = None,
        openai_client: Optional[OpenAI] = None,
        # Feature toggles
        enable_multi_query: bool = True,
        enable_hyde: bool = True,
        enable_bm25: bool = True,
        enable_reranking: bool = True,
        enable_glossary_expansion: bool = True,
        # Tuning parameters
        dense_top_k: int = 20,
        bm25_top_k: int = 20,
        rerank_top_k: int = 8,
        dense_weight: float = 0.8,
        sparse_weight: float = 0.2,
        multi_query_count: int = 2,
        question_type: str = "GENERAL",
        # Vietnamese document priority
        enable_vi_priority: bool = True,
        vi_score_boost: float = 2.0,
        vi_reserved_slots: int = 6,
    ):
        super().__init__()
        self._index = index
        self._supabase = supabase_client
        self._glossary = glossary_expander
        self._reranker = reranker
        self._openai = openai_client or OpenAI()

        # Feature toggles
        self._enable_multi_query = enable_multi_query
        self._enable_hyde = enable_hyde
        self._enable_bm25 = enable_bm25
        self._enable_reranking = enable_reranking
        self._enable_glossary = enable_glossary_expansion

        # Parameters
        self._dense_top_k = dense_top_k
        self._bm25_top_k = bm25_top_k
        self._rerank_top_k = rerank_top_k
        self._dense_weight = dense_weight
        self._sparse_weight = sparse_weight
        self._multi_query_count = multi_query_count
        self._question_type = question_type
        if question_type in ("STRUCTURE", "GENERAL", "PROCEDURE"):
            self._enable_multi_query = False
            self._enable_hyde = False

        # Vietnamese priority
        self._enable_vi_priority = enable_vi_priority
        self._vi_boost = vi_score_boost
        self._vi_reserved_slots = vi_reserved_slots

        # Initialize sub-components
        self._bm25_searcher = BM25Searcher(supabase_client) if enable_bm25 else None

        # Prefetched results for the original query (set externally)
        self._prefetched_dense = None
        self._prefetched_bm25 = None

    @staticmethod
    def _boost_vi_scores(
        candidates: list[NodeWithScore],
        vi_boost: float = 2.0,
    ) -> list[NodeWithScore]:
        """Boost Vietnamese chunk scores before reranking."""
        boosted = []
        vi_count = 0
        for n in candidates:
            if n.node.metadata.get("language") == "vi":
                boosted.append(NodeWithScore(node=n.node, score=n.score * vi_boost))
                vi_count += 1
            else:
                boosted.append(n)
        if vi_count:
            logger.info("VI priority: boosted %d VN chunks by %.1fx", vi_count, vi_boost)
        return boosted

    @staticmethod
    def _apply_slot_reservation(
        reranked: list[NodeWithScore],
        vi_reserved_slots: int = 6,
        top_k: int = 10,
    ) -> list[NodeWithScore]:
        """Reserve top slots for Vietnamese chunks after reranking."""
        vi = [n for n in reranked if n.node.metadata.get("language") == "vi"]
        vi_take = min(len(vi), vi_reserved_slots)

        result = vi[:vi_take]
        seen = {(n.node.node_id or n.node.id_) for n in result}

        for n in reranked:
            if len(result) >= top_k:
                break
            nid = n.node.node_id or n.node.id_
            if nid not in seen:
                result.append(n)
                seen.add(nid)

        logger.info(
            "VI slot reservation: %d VN reserved + %d others = %d total",
            vi_take, len(result) - vi_take, len(result),
        )
        return result

    def _dense_search(self, query: str, top_k: int) -> list[NodeWithScore]:
        """Execute dense vector search via the existing VectorStoreIndex."""
        retriever = self._index.as_retriever(similarity_top_k=top_k)
        return retriever.retrieve(query)

    def _safe_dense_search(self, query: str, top_k: int) -> list[NodeWithScore]:
        """Dense search with error handling for use in thread pool."""
        try:
            return self._dense_search(query, top_k)
        except Exception as e:
            logger.warning("Dense search failed for '%s': %s", query[:50], e)
            return []

    def _safe_bm25_search(self, query: str, top_k: int) -> list[NodeWithScore]:
        """BM25 search with error handling for use in thread pool."""
        if not self._bm25_searcher:
            return []
        try:
            return self._bm25_searcher.search(query, top_k=top_k)
        except Exception as e:
            logger.warning("BM25 search failed for '%s': %s", query[:50], e)
            return []

    def set_prefetched_results(
        self, dense_results: list[NodeWithScore], bm25_results: list[NodeWithScore]
    ):
        """Set pre-computed search results for the original query."""
        self._prefetched_dense = dense_results
        self._prefetched_bm25 = bm25_results

    def _generate_multi_query(self, query: str) -> tuple[list[str], str]:
        """Generate multi-query variants (runs in thread pool)."""
        try:
            loop = asyncio.new_event_loop()
            try:
                return loop.run_until_complete(
                    generate_query_variants(
                        self._openai, query,
                        enable_multi_query=self._enable_multi_query,
                        enable_hyde=self._enable_hyde,
                        multi_query_count=self._multi_query_count,
                    )
                )
            finally:
                loop.close()
        except Exception as e:
            logger.warning("Query variant generation failed: %s", e)
            return [], ""

    def _fuse_search_results(
        self,
        dense_results: list[list[NodeWithScore]],
        bm25_results: list[list[NodeWithScore]],
    ) -> list[NodeWithScore]:
        """Apply RRF fusion across all query results."""
        hybrid_per_query = []
        for dense, bm25 in zip(dense_results, bm25_results):
            if bm25:
                merged = reciprocal_rank_fusion(
                    dense, bm25,
                    dense_weight=self._dense_weight,
                    sparse_weight=self._sparse_weight,
                )
            else:
                merged = dense
            hybrid_per_query.append(merged)
        return merge_multi_query_results(hybrid_per_query, top_n=50)

    def _retrieve(self, query_bundle: QueryBundle) -> list[NodeWithScore]:
        """Synchronous retrieval with speculative parallel execution.

        Phase A runs initial searches in parallel with multi-query generation.
        Phase B runs searches for generated variants.
        Phase C applies fusion, filtering, and reranking.
        """
        query = query_bundle.query_str
        t0 = time.perf_counter()
        logger.info("AdvancedRetriever: processing '%s'", query[:80])

        # ── Step 1: Query Expansion (sync, <1ms) ──────────────────────
        expanded_query = query
        if self._enable_glossary and self._glossary:
            expanded_query = self._glossary.expand(query)
            if expanded_query != query:
                logger.debug("Glossary expanded: '%s'", expanded_query[:100])

        # ── Step 2: Phase A — Speculative parallel execution ──────────
        # Start searching with what we have NOW (original + expanded)
        # while simultaneously generating multi-query variants via LLM.
        initial_queries = [query]
        if expanded_query != query:
            initial_queries.append(expanded_query)

        if self._question_type == "PRINCIPLE" and len(query) > 40:
            need_multi_query = False
        else:
            need_multi_query = self._enable_multi_query or self._enable_hyde

        with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
            # Submit multi-query generation in parallel (before search)
            mq_future = None
            if need_multi_query:
                mq_future = pool.submit(self._generate_multi_query, query)

            # Phase A: use prefetched results for original query if available
            if self._prefetched_dense is not None:
                dense_results_a = [self._prefetched_dense]
                bm25_results_a = [self._prefetched_bm25 or []]
                # Search expanded query in parallel if needed
                if len(initial_queries) > 1:
                    expanded_q = initial_queries[1]
                    d_fut = pool.submit(self._safe_dense_search, expanded_q, self._dense_top_k)
                    b_fut = pool.submit(self._safe_bm25_search, expanded_q, self._bm25_top_k)
                    dense_results_a.append(d_fut.result(timeout=15))
                    bm25_results_a.append(b_fut.result(timeout=15))
                self._prefetched_dense = None
                self._prefetched_bm25 = None
                logger.info("Phase A: used prefetched results for original query")
            else:
                # No prefetch — search all initial queries
                dense_futures_a = {
                    q: pool.submit(self._safe_dense_search, q, self._dense_top_k)
                    for q in initial_queries
                }
                bm25_futures_a = {
                    q: pool.submit(self._safe_bm25_search, q, self._bm25_top_k)
                    for q in initial_queries
                }
                dense_results_a = [
                    dense_futures_a[q].result(timeout=15) for q in initial_queries
                ]
                bm25_results_a = [
                    bm25_futures_a[q].result(timeout=15) for q in initial_queries
                ]

            t_phase_a = time.perf_counter()
            logger.info(
                "Phase A done in %.3fs: %d initial queries searched + multi-query %s",
                t_phase_a - t0,
                len(initial_queries),
                "generating" if mq_future else "disabled",
            )

            # ── Step 3: Phase B — Search multi-query variants ─────────
            dense_results_b = []
            bm25_results_b = []
            multi_queries = []
            hyde_doc = ""

            if mq_future:
                multi_queries, hyde_doc = mq_future.result()
                variant_queries = list(multi_queries)
                if hyde_doc:
                    variant_queries.append(hyde_doc)

                if variant_queries:
                    # Variant queries use smaller top_k — they supplement
                    # the original query, so fewer results suffice
                    variant_dense_k = min(self._dense_top_k, 15)
                    variant_bm25_k = min(self._bm25_top_k, 15)
                    dense_futures_b = {
                        q: pool.submit(self._safe_dense_search, q, variant_dense_k)
                        for q in variant_queries
                    }
                    bm25_futures_b = {
                        q: pool.submit(self._safe_bm25_search, q, variant_bm25_k)
                        for q in variant_queries
                    }

                    dense_results_b = [
                        dense_futures_b[q].result(timeout=15) for q in variant_queries
                    ]
                    bm25_results_b = [
                        bm25_futures_b[q].result(timeout=15) for q in variant_queries
                    ]

        t_search = time.perf_counter()
        logger.info(
            "All searches done in %.3fs (variants: %d multi + %d hyde)",
            t_search - t0,
            len(multi_queries),
            1 if hyde_doc else 0,
        )

        # ── Step 4: RRF Fusion ────────────────────────────────────────
        all_dense = dense_results_a + dense_results_b
        all_bm25 = bm25_results_a + bm25_results_b
        candidates = self._fuse_search_results(all_dense, all_bm25)

        # Cap candidates to reduce reranker workload (tail candidates rarely
        # make it into the final top-K after reranking)
        if len(candidates) > 30:
            candidates = candidates[:30]

        logger.debug("Pipeline candidates after RRF: %d", len(candidates))

        # ── Step 5: Filter QA corpus BEFORE reranking ─────────────────
        pre_filter = len(candidates)
        candidates = [n for n in candidates if not is_qa_chunk(n)]
        if len(candidates) < pre_filter:
            logger.info(
                "Filtered %d QA chunks before reranking, %d remaining",
                pre_filter - len(candidates),
                len(candidates),
            )

        # ── Step 5.5: Boost Vietnamese scores (before reranking) ──────
        if self._enable_vi_priority:
            candidates = self._boost_vi_scores(candidates, self._vi_boost)

        # ── Step 6: Rerank ────────────────────────────────────────────
        if self._enable_reranking and self._reranker:
            final = self._reranker.rerank(query, candidates, top_k=self._rerank_top_k)
        else:
            final = candidates[:self._rerank_top_k]

        # ── Step 6.5: Slot reservation for Vietnamese chunks ─────────
        if self._enable_vi_priority:
            final = self._apply_slot_reservation(
                final, self._vi_reserved_slots, self._rerank_top_k,
            )

        t_total = time.perf_counter()
        logger.info(
            "AdvancedRetriever: %d nodes from %d candidates in %.3fs",
            len(final), len(candidates), t_total - t0,
        )
        return final
