"""Contextual Chunking: augment each chunk with LLM-generated context.

Implements the Anthropic Contextual Retrieval technique:
Before embedding, each chunk is prefixed with a short context paragraph
generated by an LLM that has access to the full source document. This
context includes:
  1. What section/topic the chunk belongs to
  2. Bilingual synonyms (Vietnamese + English) for key technical terms
  3. Related concepts that a user might search for

This dramatically reduces vocabulary mismatch and concept gap failures
because the augmented text contains multiple surface forms of each concept.

Reference: https://www.anthropic.com/news/contextual-retrieval
"""

import logging
from typing import Callable, Optional

from openai import OpenAI

logger = logging.getLogger(__name__)

# Prompt designed for wind turbine domain, bilingual VN+EN
CONTEXT_PROMPT = """\
<document>
{whole_document}
</document>

Here is a chunk extracted from the document above:
<chunk>
{chunk_text}
</chunk>

Write a short context paragraph (3-5 sentences) in the SAME LANGUAGE as the chunk \
to situate this chunk within the overall document. You MUST include:

1. Which section/chapter this chunk belongs to and its main topic.
2. Bilingual synonyms for ALL key technical terms in the chunk. For each technical \
term, provide BOTH the Vietnamese AND English equivalent. Format: "term_A (term_B)". \
Example: "hệ thống phanh (braking system)", "cánh quạt (blade)", "hộp số (gearbox)".
3. Directly related concepts that someone might search for when looking for this \
information. Include both Vietnamese and English terms.

IMPORTANT RULES:
- Include EVERY technical term's bilingual equivalent, even obvious ones.
- For physics concepts, state the key relationships (e.g., "torque is inversely \
proportional to speed" / "momen xoắn tỷ lệ nghịch với tốc độ").
- Keep it concise but terminology-rich. Prioritize synonym coverage over prose quality.
- Output ONLY the context paragraph, nothing else."""

# Lighter prompt for batch processing (fewer tokens, still effective)
CONTEXT_PROMPT_LITE = """\
<document_title>{document_title}</document_title>
<document_headings>{document_headings}</document_headings>

<chunk>
{chunk_text}
</chunk>

Write 2-3 sentences of context for this chunk. Include:
1. Section/topic it belongs to
2. Vietnamese AND English equivalents for each technical term
3. Related search terms

Output ONLY the context paragraph."""


def extract_document_title(document_text: str) -> str:
    """Extract the title (first heading) from a markdown document."""
    for line in document_text.split("\n"):
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip()
    return "Unknown Document"


def extract_headings(document_text: str, max_headings: int = 20) -> str:
    """Extract all headings from a markdown document for context."""
    headings = []
    for line in document_text.split("\n"):
        line = line.strip()
        if line.startswith("#"):
            headings.append(line)
            if len(headings) >= max_headings:
                break
    return "\n".join(headings)


def contextualize_chunk(
    client: OpenAI,
    whole_document: str,
    chunk_text: str,
    model: str = "gpt-4o-mini",
    use_lite: bool = False,
) -> str:
    """Add contextual prefix to a single chunk using LLM.

    Args:
        client: OpenAI client instance.
        whole_document: Full text of the source document.
        chunk_text: The chunk to contextualize.
        model: LLM model to use.
        use_lite: If True, use the lighter prompt (sends only title + headings
                  instead of the full document). Faster and cheaper but slightly
                  less accurate.

    Returns:
        Augmented chunk with context prefix: "[Ngữ cảnh: ...]\n{chunk_text}"
    """
    if use_lite:
        prompt = CONTEXT_PROMPT_LITE.format(
            document_title=extract_document_title(whole_document),
            document_headings=extract_headings(whole_document),
            chunk_text=chunk_text,
        )
    else:
        prompt = CONTEXT_PROMPT.format(
            whole_document=whole_document,
            chunk_text=chunk_text,
        )

    try:
        response = client.chat.completions.create(
            model=model,
            temperature=0,
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )
        context = response.choices[0].message.content.strip()
        return f"[Ngữ cảnh: {context}]\n{chunk_text}"
    except Exception as e:
        logger.warning("Failed to contextualize chunk: %s", e)
        # Fallback: return original chunk without context
        return chunk_text


def contextualize_chunks_batch(
    client: OpenAI,
    whole_document: str,
    chunks: list[str],
    model: str = "gpt-4o-mini",
    use_lite: bool = False,
    progress_callback: Optional[Callable[[int, int], None]] = None,
) -> list[str]:
    """Contextualize a batch of chunks from the same document.

    Args:
        client: OpenAI client instance.
        whole_document: Full text of the source document.
        chunks: List of chunk texts to contextualize.
        model: LLM model to use.
        use_lite: Use lighter prompt variant.
        progress_callback: Optional callback(current, total) for progress reporting.

    Returns:
        List of augmented chunks with context prefixes.
    """
    augmented = []
    total = len(chunks)

    for i, chunk in enumerate(chunks):
        result = contextualize_chunk(
            client=client,
            whole_document=whole_document,
            chunk_text=chunk,
            model=model,
            use_lite=use_lite,
        )
        augmented.append(result)

        if progress_callback:
            progress_callback(i + 1, total)

    logger.info(
        "Contextualized %d/%d chunks from document (%.0f chars)",
        len(augmented),
        total,
        len(whole_document),
    )
    return augmented
