import logging
import re
from typing import Optional

import vecs
from llama_index.core import Settings, VectorStoreIndex
from llama_index.core.chat_engine import CondensePlusContextChatEngine
from llama_index.core.chat_engine.types import BaseChatEngine

from app.services.windbot_engine import WindBotChatEngine
from llama_index.core.memory import ChatMemoryBuffer
from llama_index.core.postprocessor import SimilarityPostprocessor
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.schema import NodeWithScore, QueryBundle
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.llms.openai import OpenAI
from llama_index.llms.openai import utils as openai_llm_utils
from llama_index.vector_stores.supabase import SupabaseVectorStore
from pydantic import Field
from supabase import Client as SupabaseClient

from app.config import settings as app_settings
from app.prompts.system import get_condense_prompt, get_system_prompt
from app.services.advanced_retriever import AdvancedRetriever
from app.services.cached_embedding import CachedOpenAIEmbedding
from app.services.query_expansion import GlossaryExpander
from app.services.reranker import FlashReranker, OnnxReranker

logger = logging.getLogger(__name__)


class CorrectionOverridePostprocessor(BaseNodePostprocessor):
    """Mark retrieved nodes that conflict with user corrections.

    When corrections exist, scans each retrieved chunk and prepends
    an override notice if the chunk contains a conflicting value.
    This ensures the LLM sees the conflict explicitly.
    """

    corrections: list[dict] = Field(default_factory=list)

    def _postprocess_nodes(
        self,
        nodes: list[NodeWithScore],
        query_bundle: Optional[QueryBundle] = None,
    ) -> list[NodeWithScore]:
        if not self.corrections:
            return nodes
        for node_ws in nodes:
            text = node_ws.node.get_content().lower()
            for corr in self.corrections:
                old_val = (corr.get("old_value") or "").lower().strip()
                attr = (corr.get("attribute") or "").lower().strip()
                new_val = (corr.get("new_value") or "").lower().strip()
                entity = (corr.get("entity") or "").lower().strip()

                # Match on: old_value, attribute with different value,
                # OR entity name appearing in this chunk
                matched = False
                if old_val and old_val in text:
                    matched = True
                elif attr and attr in text and new_val and new_val not in text:
                    matched = True
                elif entity and entity in text:
                    matched = True

                if matched:
                    prefix = (
                        f"[USER CORRECTED: {corr.get('entity', '?')} — "
                        f"{corr.get('attribute', '?')}="
                        f"{corr.get('new_value', '?')}. "
                        f"IGNORE conflicting values below.]\n"
                    )
                    node_ws.node.set_content(
                        prefix + node_ws.node.get_content()
                    )
                    break
        return nodes


# Toggle: set to False to re-enable QA corpus chunks in retrieval
EXCLUDE_QA_CORPUS = True


class QACorpusFilterPostprocessor(BaseNodePostprocessor):
    """Filter out AI-generated QA corpus chunks from retrieval results.

    QA corpus was generated by GPT-4o-mini and may contain factual errors.
    Checks both metadata filename and content pattern (Q: ... A: ...).
    Toggle EXCLUDE_QA_CORPUS above to enable/disable.
    """

    def _is_qa_chunk(self, node_ws: NodeWithScore) -> bool:
        # Check metadata filename
        filename = (node_ws.node.metadata.get("filename") or "").lower()
        if filename.startswith("qa"):
            return True
        # Check content pattern: AI-generated QA pairs start with "Q: "
        content = node_ws.node.get_content()[:50]
        if content.strip().startswith("Q:") or content.strip().startswith("Q :"):
            return True
        return False

    def _postprocess_nodes(
        self,
        nodes: list[NodeWithScore],
        query_bundle: Optional[QueryBundle] = None,
    ) -> list[NodeWithScore]:
        filtered = [n for n in nodes if not self._is_qa_chunk(n)]
        if len(filtered) < len(nodes):
            logger.info(
                "QACorpusFilter: removed %d QA chunks, kept %d",
                len(nodes) - len(filtered),
                len(filtered),
            )
        return filtered


class ContextStrippingPostprocessor(BaseNodePostprocessor):
    """Strip augmented context metadata from chunks before LLM sees them.

    Chunks stored in pgvector have a "[Ngữ cảnh: ...]" prefix added during
    ingestion for better retrieval. This prefix helps embedding search but
    confuses the LLM during generation (it may cite metadata instead of
    actual content). This postprocessor strips the prefix so the LLM only
    sees the original document content.

    Must run BEFORE SourceNumberingPostprocessor.
    """

    _CONTEXT_PREFIX = re.compile(
        r"^\[Ngữ cảnh:.*?\]\s*",
        re.DOTALL,
    )

    def _postprocess_nodes(
        self,
        nodes: list[NodeWithScore],
        query_bundle: Optional[QueryBundle] = None,
    ) -> list[NodeWithScore]:
        for node_ws in nodes:
            content = node_ws.node.get_content()
            stripped = self._CONTEXT_PREFIX.sub("", content)
            if stripped != content:
                node_ws.node.set_content(stripped)
        return nodes


class SourceNumberingPostprocessor(BaseNodePostprocessor):
    """Number retrieved nodes with clear boundaries so LLM can cite accurately.

    Wraps each node in delimiters with clean separation between
    metadata header and content body:
        --- [Source N] ---
        Tài liệu: filename, trang page
        Nội dung:
        content...
        --- END Source N ---

    Must be the LAST postprocessor in the chain.
    """

    def _postprocess_nodes(
        self,
        nodes: list[NodeWithScore],
        query_bundle: Optional[QueryBundle] = None,
    ) -> list[NodeWithScore]:
        for i, node_ws in enumerate(nodes):
            num = i + 1
            node_ws.node.metadata["source_number"] = num
            original = node_ws.node.get_content()
            filename = node_ws.node.metadata.get("filename", "")
            page = node_ws.node.metadata.get("page", "")
            page_str = f", trang {page}" if page else ""
            node_ws.node.set_content(
                f"--- [Source {num}] ---\n"
                f"Tài liệu: {filename}{page_str}\n"
                f"Nội dung:\n"
                f"{original}\n"
                f"--- END Source {num} ---"
            )
        return nodes


# Newer OpenAI models not yet in llama_index's hardcoded registry
_CUSTOM_MODELS = {
    "gpt-4.1-mini": 1_000_000,
    "gpt-4.1-nano": 1_000_000,
    "gpt-4.1": 1_000_000,
    "gpt-5.4-mini-2026-03-17": 1_000_000,
}


def configure_settings():
    """Set global LlamaIndex settings."""
    # Register custom models so llama_index accepts them
    for name, ctx in _CUSTOM_MODELS.items():
        if name not in openai_llm_utils.ALL_AVAILABLE_MODELS:
            openai_llm_utils.ALL_AVAILABLE_MODELS[name] = ctx
            openai_llm_utils.CHAT_MODELS[name] = ctx

    Settings.llm = OpenAI(model=app_settings.llm_model, temperature=0, additional_kwargs={"seed": 42})
    logger.info("LLM model: %s", app_settings.llm_model)
    Settings.embed_model = CachedOpenAIEmbedding(model="text-embedding-3-small", cache_size=200)
    Settings.chunk_size = 1024
    Settings.chunk_overlap = 200


def create_vector_store(connection_string: str) -> SupabaseVectorStore:
    """Create a Supabase vector store instance."""
    vector_store = SupabaseVectorStore(
        postgres_connection_string=connection_string,
        collection_name="wind_turbine_docs",
        dimension=1536,
    )

    # Create cosine distance index to avoid full table scans
    try:
        vx = vecs.create_client(connection_string)
        collection = vx.get_or_create_collection(
            "wind_turbine_docs", dimension=1536
        )
        collection.create_index(
            measure=vecs.IndexMeasure.cosine_distance, replace=False
        )
        logger.info("Vector index verified/created for cosine distance")
    except Exception as e:
        logger.warning("Could not create vector index: %s", e)

    return vector_store


def create_index(vector_store: SupabaseVectorStore) -> VectorStoreIndex:
    """Create a VectorStoreIndex from an existing vector store."""
    return VectorStoreIndex.from_vector_store(vector_store)


def get_chat_engine(
    index: VectorStoreIndex,
    language: str = "en",
    has_history: bool = False,
    corrections_block: str = "",
    corrections: Optional[list[dict]] = None,
    chat_history: Optional[list] = None,
    supabase_client: Optional[SupabaseClient] = None,
    glossary_expander: Optional[GlossaryExpander] = None,
    reranker: Optional[FlashReranker | OnnxReranker] = None,
    question_type: str = "GENERAL",
) -> BaseChatEngine:
    """Create a chat engine using condense_plus_context mode.

    Uses "condense_plus_context" mode which automatically condenses
    follow-up questions into standalone queries before retrieval.
    This ensures short/ambiguous follow-ups like "có thể có 4 ko?"
    are reformulated into clear queries (e.g., "Tua-bin gió có thể
    có 4 cánh quạt không?") before hitting the vector store.

    When advanced retrieval is enabled, the default VectorStoreIndex
    retriever is replaced with AdvancedRetriever which adds:
    - Glossary-powered query expansion
    - Multi-query + HyDE generation
    - Hybrid search (dense + BM25)
    - Cross-encoder reranking

    Args:
        index: The VectorStoreIndex to query against.
        language: Language for system prompt and metadata filtering ("en" or "vi").
        has_history: Whether the conversation has prior messages.
        corrections_block: Formatted corrections to inject into system prompt.
        corrections: Raw correction dicts for node post-processing.
        chat_history: Prior chat messages to pre-load into memory.
        supabase_client: Supabase client for BM25 search (advanced mode).
        glossary_expander: GlossaryExpander instance (advanced mode).
        reranker: FlashReranker instance (advanced mode).
    """
    memory = ChatMemoryBuffer.from_defaults(
        token_limit=8000,
        chat_history=chat_history,
    )
    system_prompt = get_system_prompt(
        language,
        corrections_block=corrections_block,
        question_type=question_type,
    )

    # Choose retriever: advanced pipeline or legacy dense-only
    use_advanced = (
        app_settings.enable_advanced_retrieval
        and supabase_client is not None
    )

    postprocessors = []
    # QA corpus filter for BOTH modes. QA chunks (GPT-generated) always
    # outscore original document chunks in reranking because they are
    # perfect Q&A pairs. This prevents the chatbot from ever retrieving
    # actual source documents (AWEA, ABS FOWT, etc.). Original documents
    # are the authoritative source; QA corpus is supplementary only.
    if EXCLUDE_QA_CORPUS:
        postprocessors.append(QACorpusFilterPostprocessor())
    # SimilarityPostprocessor only for legacy mode — in advanced mode the
    # reranker already handles relevance scoring (and uses a different score
    # scale, so the 0.25 cosine cutoff would incorrectly filter results).
    if not use_advanced:
        postprocessors.append(SimilarityPostprocessor(similarity_cutoff=0.25))
    if corrections:
        postprocessors.append(
            CorrectionOverridePostprocessor(corrections=corrections)
        )
    postprocessors.append(ContextStrippingPostprocessor())  # Strip augmented metadata
    postprocessors.append(SourceNumberingPostprocessor())  # Must be last

    if use_advanced:
        retriever = AdvancedRetriever(
            index=index,
            supabase_client=supabase_client,
            glossary_expander=glossary_expander,
            reranker=reranker,
            enable_multi_query=app_settings.enable_multi_query,
            enable_hyde=app_settings.enable_hyde,
            enable_bm25=app_settings.enable_bm25,
            enable_reranking=app_settings.enable_reranking,
            enable_glossary_expansion=app_settings.enable_glossary_expansion,
            dense_top_k=app_settings.dense_top_k,
            bm25_top_k=app_settings.bm25_top_k,
            rerank_top_k=app_settings.rerank_top_k,
            dense_weight=app_settings.dense_weight,
            sparse_weight=app_settings.sparse_weight,
            multi_query_count=app_settings.multi_query_count,
            question_type=question_type,
            enable_vi_priority=app_settings.enable_vi_priority,
            vi_score_boost=app_settings.vi_score_boost,
            vi_reserved_slots=app_settings.vi_reserved_slots,
        )
        logger.info("Using AdvancedRetriever (hybrid search + reranking)")

        chat_engine = WindBotChatEngine.from_defaults(
            retriever=retriever,
            memory=memory,
            system_prompt=system_prompt,
            condense_prompt=get_condense_prompt(language),
            node_postprocessors=postprocessors,
            verbose=False,
        )
    else:
        # Legacy mode: dense-only retrieval via index.as_chat_engine()
        if use_advanced is False and app_settings.enable_advanced_retrieval:
            logger.warning(
                "Advanced retrieval enabled but supabase_client not provided. "
                "Falling back to legacy dense-only mode."
            )
        chat_engine = index.as_chat_engine(
            chat_mode="condense_plus_context",
            memory=memory,
            similarity_top_k=10,
            system_prompt=system_prompt,
            node_postprocessors=postprocessors,
            condense_prompt=get_condense_prompt(language),
            verbose=False,
        )

    return chat_engine
